#!/bin/groovy
/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this file
 * except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */

pipeline {
    agent {
        label 'orion'
    }
    options {
        disableConcurrentBuilds()
        timestamps()
        ansiColor('xterm')
    }
    environment {
        dns1 = "192.168.106.10"
        dns2 = "192.168.106.12"
        vm_display = "False"
        vm_template = "CN-CI-4G"
        spgw_kernel_version = "kernel-4.9"
        mme_vm_template = "template${vm_template}"
        hss_vm_template = "template${vm_template}"
        spgw_vm_template = "template${vm_template}-${spgw_kernel_version}"
    }

    stages {
        stage ('Verify Parameters') {
            steps {
                script {
                    echo '\u2705 \u001B[32mVerify Parameters\u001B[0m'
                    echo "Git URL    is ${GIT_URL}"
                    echo "Git Branch is ${GIT_BRANCH}"
                    echo "Git Commit is ${GIT_COMMIT}"
                    echo "Node       is ${NODE_NAME}"

                    def allParametersPresent = true

                    if (params.ToolGitLabRepository_Credentials == null) {
                        allParametersPresent = false
                    }
                    if (allParametersPresent == false) {
                        echo '\u26D4 \u001B[31;1m Cannot retrieve Private GitLab w/ tools without credentials\u001B[0m \u2639'
                        sh "exit EXIT_FAILURE"
                    }
                }
            }
        }
        stage ('Retrieve Source Code') {
            steps {
                    sh "sudo sak4ci init  --management-nw '192.168.21.0/24'"
            }
        }
    }
}

def getRepoURL() {
  sh "git config --get remote.origin.url > .git/remote-url"
  return readFile(".git/remote-url").trim()
}

def getCommitSha() {
  sh "git rev-parse HEAD > .git/current-commit"
  return readFile(".git/current-commit").trim()
}

def updateGithubCommitStatus(build, jobMessage) {
  // workaround https://issues.jenkins-ci.org/browse/JENKINS-38674
  repoUrl = getRepoURL()
  commitSha = getCommitSha()

  step([
    $class: 'GitHubCommitStatusSetter',
    reposSource: [$class: "ManuallyEnteredRepositorySource", url: repoUrl],
    commitShaSource: [$class: "ManuallyEnteredShaSource", sha: commitSha],
    errorHandlers: [[$class: 'ShallowAnyErrorHandler']],
    statusResultSource: [
      $class: 'ConditionalStatusResultSource',
      results: [
        [$class: 'AnyBuildResult', state: build.currentResult, message: jobMessage]
      ]
    ]
  ])
}

