// Temporary script to build OpenAirInterface Core Network
// Author    : Raphael Defosseux
// Copyright : OpenAirInterface Software Alliance (2018)
// Version   : 0.1

pipeline {
    // Currently using abeille with Raphael's credentials
    // We need to investigate how to use Orion concurrently with development efforts
    agent {
        label 'abeille'
    }
    options {
        disableConcurrentBuilds()
        timestamps()
    }
    environment {
        dns1 = "192.168.106.10"
        dns2 = "192.168.106.12"
        vm_display = "False"
    }

    stages {
        stage ('Verify Parameters') {
            steps {
                echo 'Verify Parameters'
                echo "Base URL   is ${JENKINS_URL}"
                echo "Git Branch is ${GIT_BRANCH}"
                echo "Git Commit is ${GIT_COMMIT}"
                echo "Git URL    is ${GIT_URL}"
                sh "mkdir ${WORKSPACE}/tmp
            }
        }
        stage ('Retrieve Source Code') {
            dir ('tmp') {
                steps {
                    sh "sudo sak4ci init  --management-nw '192.168.21.0/24'"
                    sh "sudo sak4ci scm --job-name ${JOB_NAME} --build-id ${BUILD_NUMBER} -u ${GIT_URL} -C ${GIT_COMMIT}"
                }
            }
        }
    }
    post {
        always {
            dir ('tmp') {
                deleteDir()
            }
        }
    }
}
