// Temporary script to build OpenAirInterface Core Network
// Author    : Raphael Defosseux
// Copyright : OpenAirInterface Software Alliance (2018)
// Version   : 0.1

pipeline {
    // Currently using abeille with Raphael's credentials
    // We need to investigate how to use Orion concurrently with development efforts
    agent {
        label 'abeille'
    }
    options {
        disableConcurrentBuilds()
        timestamps()
    }
    environment {
        dns1 = "192.168.106.10"
        dns2 = "192.168.106.12"
        vm_display = "False"
    }

    stages {
        stage ('Verify Parameters') {
            steps {
                echo 'Verify Parameters'
                echo "Git URL    is ${GIT_URL}"
                echo "Git Branch is ${GIT_BRANCH}"
                echo "Git Commit is ${GIT_COMMIT}"
                script {
                    if (params.nodeToUse == '') {
                       echo "Node is not defined"
                    } else {
                       echo "Node is defined w/ ${params.nodeToUse}"
                    }
                }
                sh "sudo mkdir -p ${WORKSPACE}/tmp"
            }
        }
        stage ('Retrieve Source Code') {
            steps {
                dir ('tmp') {
                    sh "sudo sak4ci init  --management-nw '192.168.21.0/24'"
                    sh "sudo sak4ci scm --job-name ${JOB_NAME} --build-id ${BUILD_NUMBER} -u ${GIT_URL} -C ${GIT_COMMIT}"
                }
            }
        }
    }
    post {
        success {
            updateGithubCommitStatus(currentBuild, "Build job completed")
        }
        failure {
            updateGithubCommitStatus(currentBuild, "One step of job failed")
        }
        unstable {
            updateGithubCommitStatus(currentBuild, "One step of job is unstable")
        }
        aborted {
            updateGithubCommitStatus(currentBuild, "Build job aborted: pipeline script issue?")
        }
        cleanup {
            dir ('tmp') {
                sh "sudo sak4ci clean-build --job-name ${JOB_NAME} --build-id ${BUILD_NUMBER}"
            }
            sh "sudo rm -Rf ${WORKSPACE}/tmp"
        }
    }
}

def getRepoURL() {
  sh "git config --get remote.origin.url > .git/remote-url"
  return readFile(".git/remote-url").trim()
}

def getCommitSha() {
  sh "git rev-parse HEAD > .git/current-commit"
  return readFile(".git/current-commit").trim()
}

def updateGithubCommitStatus(build, jobMessage) {
  // workaround https://issues.jenkins-ci.org/browse/JENKINS-38674
  repoUrl = getRepoURL()
  commitSha = getCommitSha()

  step([
    $class: 'GitHubCommitStatusSetter',
    reposSource: [$class: "ManuallyEnteredRepositorySource", url: repoUrl],
    commitShaSource: [$class: "ManuallyEnteredShaSource", sha: commitSha],
    errorHandlers: [[$class: 'ShallowAnyErrorHandler']],
    statusResultSource: [
      $class: 'ConditionalStatusResultSource',
      results: [
        [$class: 'AnyBuildResult', state: build.currentResult, message: jobMessage]
      ]
    ]
  ])
}

